witmy: &witmy
  docker:
    - image: circleci/node:10.14.2
    
version: 2
jobs:
  build:
    <<: *witmy
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build app in production mode
          command: |
            yarn build

      - persist_to_workspace:
          root: .
          paths:
          - .
  deploy:
    <<: *witmy
    steps:
      - attach_workspace:
          at: .

      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=1//0g1hdqtSbZ4cLCgYIARAAGBASNwF-L9Ir6dyvoGjX20XLeu0h1hq0ECdk9RIfNR0iRH2afIL8m9zmceYIe-mi6IuxkC_Sg21WFoQ

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master